PyDemo:
  # é¦–æ¬¡ä¼šæ ¹æ®æ¥å£æ•°æ®åŒ…ç”Ÿæˆï¼Œå¯è‡ªè¡Œæ›´æ”¹æˆ–æ·»åŠ æ–°é…ç½®ï¼Œæ‰€æœ‰é…ç½®å°†ç”¨äºå…¬å…±å…³è”å€¼ã€‚
  timeout: 10
  scheme: http
  headers:
    Content-Type: application/x-www-form-urlencoded;charset=UTF-8
  headtoken: xu5YwIZFkVGczMn0H0rot2ps7zRIbvrTHNwMXx1sJXg=

#================================ğŸ‘‡testğŸ‘‡=====================================
  # æµ‹è¯•ç¯å¢ƒ
  operating: test
  host: test.263live.net

#================================ğŸ‘†testğŸ‘†=====================================

#ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼testç¯å¢ƒè·Ÿliveç¯å¢ƒåªèƒ½åŒæ—¶å¼€æ”¾ä¸€ä¸ªï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼ï¼

#================================ğŸ‘‡liveğŸ‘‡=====================================
  # ç”Ÿäº§ç¯å¢ƒ
  # operating: live
  # host:
#================================ğŸ‘†liveğŸ‘†=====================================